---
- hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Update all packages
      package:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install JDK and ElasticSearch
      yum:
        name: [
        'java-1.8.0-openjdk-devel',
        'https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.2.rpm'
        ]
        state: installed

    - name: Install discovery-ec2 plugin
      shell: yes | ./elasticsearch-plugin install discovery-ec2 -s
      args:
        chdir: /usr/share/elasticsearch/bin

    - name: Copy elasticsearch.yml
      copy:
        src: ../files/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml

    - name: Create certs directory
      file:
        path: /etc/elasticsearch/certs
        state: directory

    - name: Create CA cert
      shell: ./elasticsearch-certutil ca --pass insecure --out /etc/elasticsearch/certs/es-demo-ca.p12
      args:
        chdir: /usr/share/elasticsearch/bin

    - name: Create node cert
      shell: ./elasticsearch-certutil cert -ca /etc/elasticsearch/certs/es-demo-ca.p12 --ca-pass insecure --pass "" --out /etc/elasticsearch/certs/es-demo-node.p12
      args:
        chdir: /usr/share/elasticsearch/bin

    - name: Set cert ownership
      file:
        path: /etc/elasticsearch/certs/es-demo-ca.p12
        mode: 0744

    - name: Set cert ownership
      file:
        path: /etc/elasticsearch/certs/es-demo-node.p12
        mode: 0744

    - name: Create demo user
      shell: ./elasticsearch-users useradd demo -p demopass -r superuser
      args:
        chdir: /usr/share/elasticsearch/bin

    - name: Create override dir
      file:
        path: /etc/systemd/system/elasticsearch.service.d
        state: directory
        mode: 0755

    - name: Copy systemd override
      copy:
        src: ../files/override.conf
        dest: /etc/systemd/system/elasticsearch.service.d/override.conf

    - name: Enable ES Service
      systemd:
        name: elasticsearch
        enabled: yes
        daemon_reload: yes