cluster.name: es-demo
node.name: ${HOSTNAME}
network.host: _ec2:privateIpv4_
discovery.zen.hosts_provider: ec2
cloud.node.auto_attributes: true
cluster.routing.allication.awareness.attributes: aws_availability_zone
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch